### ISSUE TITLE
Cold Storage and Data Archiving

### ISSUE THREAD

**Issue by leihchen** [operate-first/curator#131]
Cold Data Archiving
1. Leave the detached table in the database. This requires no further effort from the user or cluster. Detached partitions remain accessible in the PostgreSQL database. 

2. If a user wants to move old data out of the database into a local machine. Users can do this by running following commands to export the data to the local disk.

    ```
    pg_dump --table logs2_y2021m02
    ```

    After exporting, users can run DROP TABLE to delete old partitions in PostgreSQL.

    ```
    DROP TABLE logs2_y2021m02;
    ```

3. Similar to 2.2, old data is archived in local disk outside of the cluster. Users can configure a local volume destination when setting up Curator. A cronjob will export and delete data in PostgreSQL in each archiving period.

**Comment by hpdempsey** [comment]
This issue needs a definition of done.  What we were looking for was a written design analysis of the options, how they would fit into Operate First (e.g. version compatibility), and what development work (including documentation and testing) would be needed to provide cold data archiving as a feature.  The feature also needs a more detailed definition.
