### ISSUE TITLE
Investigate failure and log error properly

### ISSUE THREAD

**Issue by leihchen** [operate-first/curator#153]
I notice a data transfer failure happened on Nov 1 while inspecting the `history` table: 
| file\_names | success | crtime |
| :--- | :--- | :--- |
| 20211031T211152-cost-mgmt.tar.gz | true | 2021-11-01 00:00:08.061158 |
| **_20211101T031403-cost-mgmt.tar.gz_** | **_false_** | **_2021-11-01 06:00:07.956427_** |
| 20211101T091612-cost-mgmt.tar.gz | true | 2021-11-01 12:00:07.347635 |
| 20211101T151831-cost-mgmt.tar.gz | true | 2021-11-01 18:00:07.067442 |

We need to investigate this incident.
In the current design, the curator will do his job in the best effort **without** firing up an exception to the cluster. This cause some problem for debugging since the cluster GC discards a pod (including contexts and logs) that has been executed successfully. I think we should handle internal mistakes like this so that users are aware of any errors.

**Comment by leihchen** [comment]
Metrics data from `2021-10-31 20:59:59.000000` to `2021-11-01 03:00:00.000000` is lost.

**Comment by gagansk** [comment]
If the error doesn't show up by 11/19, close this issue.

**Comment by leihchen** [comment]
Since report is collected every 6 hours. It’s possible to have reports from 2 different months in a batch upload. For example, in the first report collection of Dec, metrics from Nov and Dec are separated into 2 tables.

An example cost-mgmt report causing this problem:

20211201T060041-cost-mgmt
|--    9237ce8f-0d19-440a-b315-524b59948f59_openshift_usage_report.0.csv    **# Nov 30 node report**
|--    9237ce8f-0d19-440a-b315-524b59948f59_openshift_usage_report.2.csv    **# Nov 30 namespace report**
|--    9237ce8f-0d19-440a-b315-524b59948f59_openshift_usage_report.4.csv    **# Nov 30 cpu/memory report**
|--    9237ce8f-0d19-440a-b315-524b59948f59_openshift_usage_report.6.csv    **# Nov 30 storage report**
|--    9237ce8f-0d19-440a-b315-524b59948f59_openshift_usage_report.1.csv    **# Dec 01 node report**
|--   9237ce8f-0d19-440a-b315-524b59948f59_openshift_usage_report.3.csv    **# Dec 01 namespace report**
|--    9237ce8f-0d19-440a-b315-524b59948f59_openshift_usage_report.5.csv    **# Dec 01 cpu/memory report**
|--    9237ce8f-0d19-440a-b315-524b59948f59_openshift_usage_report.7.csv    **# Dec 01 storage report**
|--    manifest.json
