### ISSUE TITLE
Remote shell failure in Curator cluster

### ISSUE THREAD

**Issue by leihchen** [operate-first/curator#165]
Remote shell pod access is failing on Curator Cluster.
To repeat this error:
```
$ oc rsh <any running pod>;
  Error from server (InternalError): Internal error occurred: failed calling webhook "validate-exec.devworkspace-controller.svc": Post "https://devworkspace-webhookserver.openshift-operators.svc:443/validate?timeout=30s": dial tcp 10.128.2.33:8443: connect: connection refused
```

**Comment by larsks** [comment]
The error related to a webhook that was presumably installed by the "web terminal" operator, which relies on "devworkspace". I've tried removing the operator but the error persists; however, I see no webhooks in the output of either `oc get -A mutatingwebhookconfigurations` or `oc get -A validatingwebhookconfigurations` that seems relevant.

Asking around  to see if anyone has suggestions.

**Comment by leihchen** [comment]
Thank you!

**Comment by larsks** [comment]
The instructions for cleanly removing the web terminal operator are in https://access.redhat.com/documentation/en-us/openshift_container_platform/4.6/html/web_console/odc-about-web-terminal. The key instructions were:

```
$ oc delete mutatingwebhookconfigurations controller.devfile.io
$ oc delete validatingwebhookconfigurations controller.devfile.io
```

It is now possible to `oc rsh` into running pods.

This fix is temporary; I'll submit a PR to permanently remove this operator.

**Comment by larsks** [comment]
This will close automatically when https://github.com/operate-first/apps/pull/1386 merges, at which point the problem will be permanently resolved.
