### ISSUE TITLE
Define a PRD and get it approved by the cost management PM

### ISSUE THREAD

**Issue by gagansk** [operate-first/curator#172]
A PRD should be written for the Operator Development with a features list in a Google Doc.

DoD:
- Curator team needs to approve.
- Sergio needs to approve.
- Cost Management Engg team needs to approve.

Deadline: 02/09/2022

**Comment by gagansk** [comment]
The draft is being prepared here : https://docs.google.com/document/d/1JdIM7jf8mMi5as8ZZX84Mjw5m5-U45WyhHWkeIoCuRQ/edit?usp=sharing

**Comment by quaid** [comment]
> The draft is being prepared here : https://docs.google.com/document/d/1JdIM7jf8mMi5as8ZZX84Mjw5m5-U45WyhHWkeIoCuRQ/edit?usp=sharing
> 

Hi I was trying to figure out what is going on in this issue, but the Google doc is locked from being able to read it. May I recommend project materials be at least read-only for the public view?

**Comment by gagansk** [comment]
@quaid The document is available for Red Hatters. I got a request from 'karstenwade@gmail.com'. 

We are working towards developing MVP and we will make an announcement by the second week of June 2022 to the Operate First community.
