### ISSUE TITLE
Create a document on requirement to build an operator.

### ISSUE THREAD

**Issue by skanthed** [operate-first/curator#173]
Document to build and deploy operator with the sample message like "Hello-world"

- Update the document with more detailed research about Helm, GO. [Feb 7]

The current version of the curator is 
- Using database
- Using CRD implementation

**Comment by gagansk** [comment]
@skanthed Can you explain what do you mean by `Use CRD implementation` while building an Operator?

**Comment by skanthed** [comment]
Tried to build an operator and understand it’s architecture and flow -

https://docs.google.com/document/d/1dl5RffWSl9O--9DYx0VVKE5N_m125uEQzFgJzsrkHMc/edit?usp=sharing

**Comment by hpdempsey** [comment]
Please take a look at this ARD for Operate First, which lists several requirements, and points to other references as well:  https://www.operate-first.cloud/blueprints/blueprint/adr/0011-operators.md

**Comment by skanthed** [comment]
I already read this. By EOD I will update the doc with more information. I was understanding olm deployments and learning more.
