### ISSUE TITLE
Learning - Build a 'Hello World' Operator

### ISSUE THREAD

**Issue by gagansk** [operate-first/curator#178]
Engineers in the Curator team should understand how to build an Operator. 
DoD: Deploy the Operators in the development cluster. 

- [ ] @skanthed   [Feb 7]
- [ ] @ajinkyababar

**Comment by skanthed** [comment]
Yesterday was able to deploy Memcached-operator working on deploying a hello-world operator.

**Comment by ajinkyababar** [comment]
Unable to deploy operator, because facing problem with laptop, cant open any installed application e.g Chrome, VScode

**Comment by skanthed** [comment]
Deployment is all set. Learning the OLM Integration and trying to run it in bundle format.
