### ISSUE TITLE
SQL Server initialization  

### ISSUE THREAD

**Issue by skanthed** [operate-first/curator#18]
Working on database design and how hourly, weekly and monthly reports will be generated and stored.

**Comment by gagansk** [comment]
@skanthed I don't see any relevant work regarding this issue. Can we close it?

**Comment by gagansk** [comment]
Acceptance criteria:
- A SQL server should have the data that can be queried from an external end-point.
- For DB schema, refer https://github.com/operate-first/curator/blob/main/curator-documentation/ReportsLifecycle.md

**Comment by gagansk** [comment]
Closing this issue and tracking the progress in #52
