### ISSUE TITLE
Transfer to persistent storage inside the cluster

### ISSUE THREAD

**Issue by skanthed** [operate-first/curator#25]

**Comment by gagansk** [comment]
@skanthed We need to store CSV files outside the cluster.

**Comment by skanthed** [comment]
Yes, I agree to point of have it outside the cluster. So, If the cluster goes down we don't lose it. Persistent storage is like just having a local volume in the cluster. I just tried to create PV claim and tied that up with a pod. Tried to mouth path to different storage in a cluster rather than koku-metric-operator own storage. As we are moving with S3 storage. This issue can be closed.
