### ISSUE TITLE
Automate report storage in S3 Kaizen-OpenStack

### ISSUE THREAD

**Issue by gagansk** [operate-first/curator#26]

**Comment by gagansk** [comment]
Dod:

- Hourly Reports should be saved in the Swift 
- Reports should be accessible through the Curl command
- A separate folder should be created in Swift for the unzipped reports

**Comment by skanthed** [comment]
All reports that are generated by koku-metrics-operator are converted into tar files. We are planning to save all zipped files in S3 compatible storage. I plan to use the Python boto library, which connects through the S3 API interface and saves all the files in kaizen-OpenStack storage.

**Comment by skanthed** [comment]
We have a cron job that runs in OpenShift and stores the reports generated by the koku-metrics operator to the S3 bucket in OpenStack. Cron job right now runs hourly and we will make it to run daily.
