### ISSUE TITLE
Credentials should be defined in a secret and not in a file

### ISSUE THREAD

**Issue by chargio** [operate-first/curator#43]
Configuring the credentials to the S3 buckets should be secure. Currently you store them in a secrest.yml file.

instead, it would be better to use a secret in the enviornment. The credentials file could use the secrets in it (if configured to do so), or be configured using a secret, and allowing Kubernetes to take care of storing the secrets.

**Comment by chargio** [comment]
https://12factor.net/config

**Comment by skanthed** [comment]
I think it's already a secret. We pulled the environment variable into the secret generator. Which results in secret and once it's deployed is imported into a cron job.
Is this what you meant if not can you please clarify more?

**Comment by chargio** [comment]
In OpenShift, you can create secrets, that can be independently managed and
will be available inside.
You can create policies that make this secure, and they can be changed
without changes in the code, as suggested by 12-factor apps

https://kubernetes.io/docs/concepts/configuration/secret/

Regards

**Comment by larsks** [comment]
@chargio can you point at the particular code in this repository to which you're referring? The backup pod, for example, is already using Kubernetes secrets (see e.g. https://github.com/operate-first/curator/blob/main/cronjob.yaml#L21).

**Comment by chargio** [comment]
Actually, is the description in the repo itself, that asks the customer to
copy credentials into a credentials.yml file.

Sergio Ocón-Cárdenas

He / Him / His

Senior Principal Product Manager, Hybrid Cloud Business Services

Red Hat <https://www.redhat.com/>

***@***.***
M: +34-692058130
<https://www.redhat.com/>

**Comment by skanthed** [comment]
We are already passing secret to OpenShift not the credentials for sure. We will update the documentation and specify it clearly over there as we talked.

**Comment by skanthed** [comment]
Updated readme in v0.3.
