### ISSUE TITLE
Sanity check for reports against the cluster

### ISSUE THREAD

**Issue by gagansk** [operate-first/curator#86]
Compare a daily report against the actual cluster usage.

DoD:

* Tag the daily report considered for testing and the snapshot of the actual cluster usage.
* Raise an issue if there is a difference in the data without any change in the workload.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200965343172825/1200984526831722) by [Unito](https://www.unito.io)

**Comment by skanthed** [comment]
Node usage of pods from project openshift-multus -

<pre>oc get pods -n openshift-multus -o wide
NAME                                READY   STATUS    RESTARTS   AGE    IP               NODE        NOMINATED NODE   READINESS GATES
multus-95vxn                        1/1     Running   0          164d   192.12.185.177   os-ctrl-2   &lt;none&gt;           &lt;none&gt;
multus-admission-controller-kmmq2   2/2     Running   0          164d   10.128.0.9       os-ctrl-0   &lt;none&gt;           &lt;none&gt;
multus-admission-controller-lsvh9   2/2     Running   0          164d   10.129.0.26      os-ctrl-2   &lt;none&gt;           &lt;none&gt;
multus-admission-controller-rk2pm   2/2     Running   0          164d   10.130.0.38      os-ctrl-1   &lt;none&gt;           &lt;none&gt;
multus-clrz2                        1/1     Running   0          164d   192.12.185.176   os-ctrl-1   &lt;none&gt;           &lt;none&gt;
multus-hv94n                        1/1     Running   0          164d   192.12.185.175   os-ctrl-0   &lt;none&gt;           &lt;none&gt;
network-metrics-daemon-fdnhw        2/2     Running   0          164d   10.130.0.10      os-ctrl-1   &lt;none&gt;           &lt;none&gt;
network-metrics-daemon-lsmzm        2/2     Running   0          164d   10.128.0.14      os-ctrl-0   &lt;none&gt;           &lt;none&gt;
network-metrics-daemon-tpx5c        2/2     Running   0          164d   10.129.0.36      os-ctrl-2   &lt;none&gt;           &lt;none&gt;
</pre>

Pods cpu and memory usage for openshift-multus -

<pre>oc adm top pods -n openshift-multus 
NAME                                CPU(cores)   MEMORY(bytes)   
multus-95vxn                        1m           15Mi            
multus-admission-controller-kmmq2   2m           91Mi            
multus-admission-controller-lsvh9   1m           94Mi            
multus-admission-controller-rk2pm   1m           93Mi            
multus-clrz2                        2m           15Mi            
multus-hv94n                        2m           14Mi            
network-metrics-daemon-fdnhw        0m           97Mi            
network-metrics-daemon-lsmzm        0m           92Mi            
network-metrics-daemon-tpx5c        1m           89Mi      </pre>

**Comment by skanthed** [comment]
I compared the difference between the two days' usage and It was exactly the same as generated by reports from koku-metrics-operator.

**Comment by skanthed** [comment]
Just need one more day report will be generated after a day. I created projects instead of pasting queries, projects usage will give better idea.

**Comment by gagansk** [comment]
DoD:
- Deploy v1.2 in Smog
- Generate a daily report for the Smog cluster with Koku-metrics operator for a day (12 AM - 11:59 PM)
- Get the Daily report through Curator API and check for sanity.

**Comment by skanthed** [comment]
For this to execute on the Smaug cluster. We need to have admin access to the report-system namespace. As it's required by kubebuilder to configure and execute API.
We have requested that on the Smaug cluster. Once we have that. I will attach reports generated from API

**Comment by hpdempsey** [comment]
We should sanity check the weekly and monthly reports too.  Should there be separate issues for that, or just add them here?
