### ISSUE TITLE
API Research

### ISSUE THREAD

**Issue by gagansk** [operate-first/curator#96]
Identify the API end-points and the use cases we have to address through API.

DoD:

* Attach 2-page memo highlighting the what we need from the API.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200965343172825/1200984431932917) by [Unito](https://www.unito.io)

**Comment by skanthed** [comment]
Document Link -

https://docs.google.com/document/d/1Xl5W0YxI8foX2YKDsBauSi-oLmZ6mhh_0zxXv0MDM9A/edit?usp=sharing

**Comment by gagansk** [comment]
The document looks good to me.
